name: Deploy Flask App to Render

on:
  push:
    branches:
      - main  # Trigger this workflow only on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t boston-house-pricing-app .


      # Log in to Docker Hub (for storing the image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image to Docker Hub (optional if you need registry)
      - name: Push Docker image to Docker Hub
        run: |
          docker push your-docker-image-name

      # Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -F "branch=main" \
            -F "dockerfile=Dockerfile" \
            -F "image=your-docker-image-name" \
            https://api.render.com/deploy
